### ISSUE TITLE
How to compile the crate

### ISSUE THREAD

**Issue by snylonue** [mistydemeo/libcue.rs#4]
I tried to use this crate in my program, but when I try to build it, there was an error:
` = note: LINK : fatal error LNK1181: cannot open input file 'cue.lib'`

I find the C library is not included in this crate, but I don't know how to build with it.

I've learnt rust for only a short time and I don't find anything helpful on the Internet.

**Comment by mistydemeo** [comment]
Do you still need help with this?

**Comment by snylonue** [comment]
Yes, though I am sick now, which may results in slow response.

Thanks for your reply.

**Comment by mistydemeo** [comment]
Which OS are you using? What C compiler do you have?

This crate requires you to have a copy of the C libcue library already installed; it doesn't include it.

**Comment by mabushey** [comment]
On Arch Linux, `sudo pacman -Syu libcue` works. On Debian based systems: `sudo apt install libcue-dev`. After that `cargo build` will succeed.

**Comment by snylonue** [comment]
> This crate requires you to have a copy of the C libcue library already installed; it doesn't include it.

With libcue installed, I have successfully built it. Thanks.

**Comment by mistydemeo** [comment]
You're welcome!
